@host = http://localhost:3000

get {{host}}

###
post {{host}}/college
Content-Type: application/json

{
    "name": "dope",
    "domain": "kdom@student.ac.in"
}

###
get {{host}}/college?name=h&sort=-id

###
patch {{host}}/college/6
Content-Type: application/json

{
    "domain": "kcgtech@student.ac.in"
}

###
delete {{host}}/college/14