@host = http://localhost:3000
@accessToken=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDcyNjU0OTYuOTg3MzIzLCJpYXQiOjE3MDcyMjIyOTYuOTg3MzIxOSwiaXNzIjoiZ2l0aHViLmNvbS9wcml5YW5raXNob3JlbXMvdW5pd29yayIsInN1YiI6IjQ1IiwidHlwZSI6ImFjY2VzcyJ9.dUTV3anE-YjePRdoNCpgPd5n7Hak1ymhTspCCSsmRso
@refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDk4MTQyOTYuOTg3NDAzNiwiaWF0IjoxNzA3MjIyMjk2Ljk4NzQwMywiaXNzIjoiZ2l0aHViLmNvbS9wcml5YW5raXNob3JlbXMvdW5pd29yayIsInN1YiI6IjQ1IiwidHlwZSI6InJlZnJlc2gifQ.ku_iB65U1JVQrjy0e69mTWes8q3_O4vkj8sHGwTKa6w
get {{host}}

###
post {{host}}/college
Content-Type: application/json

{
    "name": "Sathyabama University",
    "domain": "sathyabamauniv@student.ac.in"
}

###
get {{host}}/college
Authorization: Bearer {{accessToken}}

###
patch {{host}}/college/9
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "kcgtechd"
}

###
delete {{host}}/college/9