@host = http://localhost:3000
@accessToken=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDc1MDM1MzQuODAxMDQ1NCwiaWF0IjoxNzA3NDE3MTM0LjgwMTA0NDIsImlzcyI6ImdpdGh1Yi5jb20vcHJpeWFua2lzaG9yZW1zL3VuaXdvcmsiLCJzdWIiOiI1IiwidHlwZSI6ImFjY2VzcyJ9.lg5FeA1eqBZ_8Ald_a0J2hO-K_xaezLMPXCNuagY8X8
@refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTAwMDkxMzQuODAxMTU3NSwiaWF0IjoxNzA3NDE3MTM0LjgwMTE1NjUsImlzcyI6ImdpdGh1Yi5jb20vcHJpeWFua2lzaG9yZW1zL3VuaXdvcmsiLCJzdWIiOiI1IiwidHlwZSI6InJlZnJlc2gifQ.jEu_LqKwLWegZUijpUtioT-rmSfTO8Q5Rwlg1KVUUBE
get {{host}}

###
post {{host}}/college
Content-Type: application/json

{
    "name": "Sathyabama University",
    "domain": "sathyabamauniv@student.ac.in"
}

###
get {{host}}/college?name=uni
Authorization: Bearer {{accessToken}}

###
patch {{host}}/college/9
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "kcgtechd"
}

###
delete {{host}}/college/9