@host = http://localhost:3000

@accessToken= eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTg4OTE5MjUuMzQ0NDM2MiwiaWF0IjoxNzExMTE1OTI1LjM0NDQzNTcsImlzcyI6ImdpdGh1Yi5jb20vcHJpeWFua2lzaG9yZW1zL3VuaXdvcmsiLCJzdWIiOiIxMCIsInR5cGUiOiJyZWZyZXNoIn0.jvMDlIyJapALk54ijYYCTiyottAPkmC2iVsbdD51-Tc
@refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTg4OTE5MjUuMzQ0NDM2MiwiaWF0IjoxNzExMTE1OTI1LjM0NDQzNTcsImlzcyI6ImdpdGh1Yi5jb20vcHJpeWFua2lzaG9yZW1zL3VuaXdvcmsiLCJzdWIiOiIxMCIsInR5cGUiOiJyZWZyZXNoIn0.jvMDlIyJapALk54ijYYCTiyottAPkmC2iVsbdD51-Tc

###
post {{host}}/task
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data

{
    "title": "Printing problem pls help",
    "description": "print this for review",
    "category": "Document Printing",
    "Price": 100,
    "status": "open"
}

###
get {{host}}/task/47
Authorization: Bearer {{accessToken}}

###
get {{host}}/task
Authorization: Bearer {{accessToken}}

###
get {{host}}/task/user/10
Authorization: Bearer {{accessToken}}

###
get {{host}}/task/worker/12
Authorization: Bearer {{accessToken}}

###
delete {{host}}/task/2
Authorization: Bearer {{accessToken}}
