@host = http://localhost:3000

@accessToken=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjM1NjUzNDMuMjA0NzkwNiwiaWF0IjoxNzE1Nzg5MzQzLjIwNDc5MDQsImlzcyI6ImdpdGh1Yi5jb20vcHJpeWFua2lzaG9yZW1zL3VuaXdvcmsiLCJzdWIiOiIxMCIsInR5cGUiOiJyZWZyZXNoIn0.UpLh8Zhz6EvmWL3Nwcd-57hePBIQMzCGGBMBU-Y6UwA
@refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MjM1NjUzNDMuMjA0NzkwNiwiaWF0IjoxNzE1Nzg5MzQzLjIwNDc5MDQsImlzcyI6ImdpdGh1Yi5jb20vcHJpeWFua2lzaG9yZW1zL3VuaXdvcmsiLCJzdWIiOiIxMCIsInR5cGUiOiJyZWZyZXNoIn0.UpLh8Zhz6EvmWL3Nwcd-57hePBIQMzCGGBMBU-Y6UwA

###
post {{host}}/task
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data

{
    "title": "Printing problem pls help",
    "description": "print this for review",
    "category": "Document Printing",
    "Price": 100,
    "status": "open"
}

###
get {{host}}/task
Authorization: Bearer {{accessToken}}

###
get {{host}}/task
Authorization: Bearer {{accessToken}}

###
get {{host}}/task/user/10
Authorization: Bearer {{accessToken}}

###
get {{host}}/task/worker/12
Authorization: Bearer {{accessToken}}

###
delete {{host}}/task/2
Authorization: Bearer {{accessToken}}

###
post {{host}}/task/request?taskid=4&userid=5
Authorization: Bearer {{accessToken}}

###
delete {{host}}/task/request?taskid=4&userid=5
Authorization: Bearer {{accessToken}}

###
patch {{host}}/task/request/approve?taskid=3&userid=2
Authorization: Bearer {{accessToken}}

###
patch {{host}}/task/request/reject?taskid=4&userid=5
Authorization: Bearer {{accessToken}}