@host = http://localhost:3000

@accessToken=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDc0MTQ0NjMuNTE4MTY3MywiaWF0IjoxNzA3MzI4MDYzLjUxODE2NiwiaXNzIjoiZ2l0aHViLmNvbS9wcml5YW5raXNob3JlbXMvdW5pd29yayIsInN1YiI6IjUiLCJ0eXBlIjoiYWNjZXNzIn0.ZH6gg4XhtfmZwSsw5mq3bsITezMbILV0SnQmoq5Dgus
@refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDk5MjAwNjMuNTE4MjUxNywiaWF0IjoxNzA3MzI4MDYzLjUxODI1MSwiaXNzIjoiZ2l0aHViLmNvbS9wcml5YW5raXNob3JlbXMvdW5pd29yayIsInN1YiI6IjUiLCJ0eXBlIjoicmVmcmVzaCJ9.sr0-nm2ICNOLaHilXyMaijWG_7xlUMbPXPgaBsSfh0A
###
get {{host}}/user
Authorization: Bearer {{accessToken}}

###
get {{host}}/user/college/1
Authorization: Bearer {{accessToken}}
###
post {{host}}/user
Content-Type: application/json

{
    "college_id": 1,
    "name": "Test user 2",
    "mobile": "1234567896",
    "email": "20113017@student.sath.ac.in",
    "dept": "Computer Science"
}

###
patch {{host}}/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "profile_pic": "this is the pic.jpg"
}

###
delete {{host}}/user
Authorization: Bearer {{accessToken}}

###
post {{host}}/security/refreshtoken
Authorization: Bearer {{refreshToken}}