@host = http://localhost:3000

###
get {{host}}/user/13

###
get {{host}}/user/college/3

###
post {{host}}/user
Content-Type: application/json

{
    "college_id": 3,
    "name": "Brian lara",
    "mobile": "546577",
    "email": "20113027@student.sath.ac.in",
    "dept": "Computer Science"
}

###
patch {{host}}/user/1
Content-Type: application/json

{
    "dept": "Computer Science"
}

###
delete {{host}}/user/36