@host = http://localhost:3000

@accessToken=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDc5Mjg2OTkuNjIzOTE3LCJpYXQiOjE3MDc4NDIyOTkuNjIzOTE2OSwiaXNzIjoiZ2l0aHViLmNvbS9wcml5YW5raXNob3JlbXMvdW5pd29yayIsInN1YiI6IjUiLCJ0eXBlIjoiYWNjZXNzIn0.mIiCdeXEMCdWa1XDoB8n_ix9e28nioZjxxThLvhzLp8
@refreshToken=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MTA0MzQyOTkuNjIzOTQ0LCJpYXQiOjE3MDc4NDIyOTkuNjIzOTQ0LCJpc3MiOiJnaXRodWIuY29tL3ByaXlhbmtpc2hvcmVtcy91bml3b3JrIiwic3ViIjoiNSIsInR5cGUiOiJyZWZyZXNoIn0.R_w0yRGBXdlKXPk3y-ONt4vLJpfdOLRGVp21ItLbZrE"
###
get {{host}}/user
Authorization: Bearer {{accessToken}}

###
get {{host}}/user/college/1?sort=name
Authorization: Bearer {{accessToken}}
###
post {{host}}/user
Content-Type: application/json

{
    "college_id": 1,
    "name": "Test user",
    "mobile": "1234567877",
    "email": "20513017@student.sath.ac.in",
    "dept": "Computer Science"
}

###
patch {{host}}/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "kabadi"
}

###
delete {{host}}/user
Authorization: Bearer {{accessToken}}

###
post {{host}}/security/refreshtoken
Authorization: Bearer {{refreshToken}}